import { createApp } from 'vue'
// import App from './components/numbercontrol.vue'
// import App from './components/scorehighlight.vue'
// import App from './components/fruitlist.vue'
// import App from './components/trail-funcs/1-reactive.vue'
import App from './components/kotsets/values.vue'
// import App from './components/kotsets/son.vue'
// import App from './components/kotsets/fathrer.vue'
// import App from './components/kotsets/grand.vue'
createApp(App).mount('#app')